import { useState } from "react";
import { Link } from "wouter";
import type { FundraiserPlan } from "@/lib/types";
import type { PlannerFormData } from "@/lib/types";
import {
  ArrowLeft, Printer, RefreshCw, Copy, CheckCircle2,
  AlertTriangle, AlertCircle, Info, Lock, ShoppingCart,
  Clock, Users, Mail, FileText, ChevronRight, Lightbulb,
  TrendingUp, MapPin, Package, MessageSquare, Shield,
} from "lucide-react";
import { PAYMENT_LINKS, ENABLE_DEMO_UNLOCK } from "@/config/paymentLinks";
import { getUnlocked, setUnlocked, savePlanBeforePayment } from "@/lib/unlock";

// ── FREE PREVIEW LIMITS ───────────────────────────────────────
// Change these numbers to adjust what the free preview shows.
const FREE_SHOPPING_ITEMS = 5;  // how many shopping list rows to show
const FREE_WARNINGS_SHOWN = 3;  // how many risk warnings to show

interface ResultsPageProps {
  plan: FundraiserPlan;
  formData: PlannerFormData;
  onReset: () => void;
}

function fmt(n: number) {
  return n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
}

export default function ResultsPage({ plan, formData, onReset }: ResultsPageProps) {
  const [copied, setCopied] = useState(false);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [copiedSummary, setCopiedSummary] = useState(false);
  const [summaryFailed, setSummaryFailed] = useState(false);
  const [unlocked, setUnlockedState] = useState<boolean>(getUnlocked);
  const [activeTab, setActiveTab] = useState<"shopping" | "supplies" | "timeline" | "volunteers" | "email">("shopping");

  const profit = plan.estimatedProfit;
  const profitStatus = profit[1] < 0 ? "loss" : profit[0] < 0 ? "risky" : "good";

  const handleDemoUnlock = () => {
    setUnlocked();
    setUnlockedState(true);
    savePlanBeforePayment(plan, formData);
  };

  const handlePaymentCTAClick = () => {
    savePlanBeforePayment(plan, formData);
    const link = PAYMENT_LINKS.fullEventPack;
    if (link) window.location.href = link;
  };

  const handlePrintClick = () => {
    savePlanBeforePayment(plan, formData);
  };

  const copyEmailBlurb = () => {
    navigator.clipboard.writeText(plan.emailBlurb).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const copyText = (key: string, text: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedKey(key);
      setTimeout(() => setCopiedKey(null), 2500);
    });
  };

  const MEAL_LABELS: Record<string, string> = {
    hotdogs: "Hot Dogs", burgers: "Burgers", bakedPotatoes: "Baked Potatoes",
    breakfastBurritos: "Breakfast Burritos", tacos: "Tacos",
    spaghetti: "Spaghetti", pancakes: "Pancakes", custom: "Custom Meal",
  };

  const copyKeySummary = () => {
    const mealLabel = MEAL_LABELS[plan.summary.mealType] ?? plan.summary.mealType;
    const top5 = [...plan.shoppingList]
      .sort((a, b) => b.estimatedCost[1] - a.estimatedCost[1])
      .slice(0, 5);
    const sep = "─".repeat(38);
    const lines = [
      "FUNDRAISER KEY SUMMARY",
      sep,
      "",
      `Event:        ${plan.summary.eventName}`,
      `Organization: ${plan.summary.orgType}`,
      `Meal:         ${mealLabel}`,
      `Attendance:   ${plan.summary.attendance} guests (${plan.summary.adults} adults, ${plan.summary.kids} kids)`,
      `Suggested:    $${plan.summary.mealPrice} per person`,
      "",
      "FINANCIALS",
      sep,
      `Expected Revenue:  ${fmt(plan.estimatedRevenue)}`,
      `Est. Food Cost:    ${fmt(plan.costRange[0])} – ${fmt(plan.costRange[1])}`,
      `Est. Net Profit:   ${fmt(plan.estimatedProfit[0])} – ${fmt(plan.estimatedProfit[1])}`,
      "",
      "VOLUNTEERS",
      sep,
      `Adult Volunteers:  ${formData.adultVolunteers}`,
      `Student Helpers:   ${formData.studentVolunteers}`,
      "",
      "TOP SHOPPING ITEMS (by cost)",
      sep,
      ...top5.map((item, i) =>
        `${i + 1}. ${item.item} — ${fmt(item.estimatedCost[0])} – ${fmt(item.estimatedCost[1])}`
      ),
      "",
      "MAIN EXECUTION RISK",
      sep,
      plan.strategySummary.mainExecutionRisk,
      "",
      "RECOMMENDED LEADER FOCUS",
      sep,
      plan.strategySummary.recommendedFocus,
      "",
      sep,
      plan.disclaimer ??
        "These are planning estimates. Adjust for your group, appetite, store prices, and local context.",
      "Generated by Fundraiser Food Math · fundraiserfoodmath.com",
    ];

    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopiedSummary(true);
      setSummaryFailed(false);
      setTimeout(() => setCopiedSummary(false), 2500);
    }).catch(() => {
      setSummaryFailed(true);
      setTimeout(() => setSummaryFailed(false), 5000);
    });
  };

  // Free preview: top N shopping items
  const previewItems = plan.shoppingList.slice(0, FREE_SHOPPING_ITEMS);
  const hiddenItemCount = plan.shoppingList.length - FREE_SHOPPING_ITEMS;

  // Free preview: up to N warnings
  const visibleWarnings = plan.riskWarnings.slice(0, FREE_WARNINGS_SHOWN);

  return (
    <div className="results-page" data-testid="results-page">
      {/* Header */}
      <div className="results-header">
        <div className="results-header-inner">
          <Link href="/" className="back-link" data-testid="link-back-home">
            <ArrowLeft className="w-4 h-4 mr-1" /> Back to home
          </Link>
          <h1 className="results-title" data-testid="results-title">{plan.summary.eventName}</h1>
          <p className="results-subtitle" data-testid="results-subtitle">
            {plan.summary.mealType} · {plan.summary.attendance} guests · {plan.summary.orgType}
          </p>
          <div className="results-actions">
            <button onClick={onReset} className="btn-secondary" data-testid="button-edit-plan">
              <RefreshCw className="w-4 h-4 mr-2" /> Edit Plan
            </button>
            {unlocked && (
              <>
                <a
                  href="/print"
                  onClick={handlePrintClick}
                  className="btn-primary"
                  target="_blank"
                  data-testid="button-print-plan"
                >
                  <Printer className="w-4 h-4 mr-2" /> Print / Save PDF
                </a>
                <button
                  onClick={copyKeySummary}
                  className="btn-secondary"
                  data-testid="button-copy-summary"
                >
                  {copiedSummary
                    ? <><CheckCircle2 className="w-4 h-4 mr-2" /> Copied!</>
                    : <><Copy className="w-4 h-4 mr-2" /> Copy Key Summary</>}
                </button>
              </>
            )}
          </div>
          {summaryFailed && (
            <p className="results-copy-failed">
              Copy failed. Select and copy the summary manually, or try again.
            </p>
          )}
        </div>
      </div>

      {/* Risk Warnings — free preview shows up to FREE_WARNINGS_SHOWN */}
      {visibleWarnings.length > 0 && (
        <div className="warnings-section" data-testid="warnings-section">
          {visibleWarnings.map((w, i) => (
            <div key={i} className={`warning-banner warning-banner--${w.level}`} data-testid={`warning-banner-${i}`}>
              <span className="warning-icon">
                {w.level === "error" ? <AlertCircle className="w-5 h-5" /> :
                 w.level === "warning" ? <AlertTriangle className="w-5 h-5" /> :
                 <Info className="w-5 h-5" />}
              </span>
              {w.message}
            </div>
          ))}
        </div>
      )}

      {/* Summary Cards — always visible */}
      <div className="summary-cards">
        <div className="summary-card" data-testid="card-revenue">
          <div className="summary-label">Expected Revenue</div>
          <div className="summary-value summary-value--revenue">{fmt(plan.estimatedRevenue)}</div>
          <div className="summary-note">{plan.summary.attendance} guests × ${plan.summary.mealPrice}</div>
        </div>
        <div className="summary-card" data-testid="card-cost">
          <div className="summary-label">Est. Total Cost</div>
          <div className="summary-value">{fmt(plan.costRange[0])} – {fmt(plan.costRange[1])}</div>
          <div className="summary-note">Food + supplies + 5% buffer</div>
        </div>
        <div className={`summary-card summary-card--${profitStatus}`} data-testid="card-profit">
          <div className="summary-label">Est. Profit</div>
          <div className={`summary-value summary-value--${profitStatus}`}>
            {fmt(profit[0])} – {fmt(profit[1])}
          </div>
          <div className="summary-note">
            {profitStatus === "loss" ? "Consider raising price or cutting costs" :
             profitStatus === "risky" ? "Margin is tight — watch costs" :
             "Looking good!"}
          </div>
        </div>
        <div className="summary-card" data-testid="card-attendance">
          <div className="summary-label">Attendance Split</div>
          <div className="summary-value">{plan.summary.adults} adults</div>
          <div className="summary-note">{plan.summary.kids} kids / students</div>
        </div>
      </div>

      {/* Disclaimer — always visible */}
      <p className="results-disclaimer" data-testid="results-disclaimer">{plan.disclaimer}</p>

      {/* Shopping List Preview — always visible, limited */}
      <section className="results-section" data-testid="section-preview">
        <h2 className="section-heading">Shopping List Preview</h2>
        <p className="section-note">
          Showing {previewItems.length} of {plan.shoppingList.length} items.
          {!unlocked && " The complete grouped list is included in the Full Event Pack."}
        </p>
        <div className="table-wrap">
          <table className="data-table" data-testid="table-shopping-preview">
            <thead>
              <tr>
                <th>Item</th>
                <th>Quantity</th>
                <th>Est. Cost Range</th>
              </tr>
            </thead>
            <tbody>
              {previewItems.map((item, i) => (
                <tr key={i} data-testid={`row-preview-${i}`}>
                  <td>{item.item}</td>
                  <td><strong>{item.quantity}</strong></td>
                  <td>{fmt(item.estimatedCost[0])} – {fmt(item.estimatedCost[1])}</td>
                </tr>
              ))}
              {!unlocked && hiddenItemCount > 0 && (
                <tr className="table-locked-row">
                  <td colSpan={3}>
                    <span className="table-locked-msg">
                      <Lock className="w-3.5 h-3.5 mr-1.5" />
                      {hiddenItemCount} more item{hiddenItemCount !== 1 ? "s" : ""} included in the Full Event Pack
                    </span>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>

      {/* ── LOCKED SECTION ─────────────────────────────────────── */}
      {!unlocked && (
        <section className="locked-section" data-testid="locked-section">
          <div className="locked-inner">
            <div className="locked-header">
              <Lock className="locked-icon" />
              <h2 className="locked-title">Unlock the Full Event Pack</h2>
              <p className="locked-subtitle">
                Everything you need to run a smooth, well-organized fundraiser — ready to print and share.
              </p>
            </div>

            <div className="locked-features-grid">
              {[
                {
                  icon: <ShoppingCart className="w-5 h-5" />,
                  title: "Complete Shopping List",
                  desc: "Every ingredient and supply with quantities, cost estimates, and grouped by category.",
                },
                {
                  icon: <FileText className="w-5 h-5" />,
                  title: "Supplies List",
                  desc: "Plates, utensils, foil, serving trays — nothing gets forgotten.",
                },
                {
                  icon: <Clock className="w-5 h-5" />,
                  title: "Step-by-Step Prep Timeline",
                  desc: "Exactly what to do, when to start, who handles it — plus leader notes and watch-out tips for each step.",
                },
                {
                  icon: <Users className="w-5 h-5" />,
                  title: "Volunteer Role Plan",
                  desc: "Role assignments for Adult Volunteers, Parent Oversight, and Student Volunteers.",
                },
                {
                  icon: <Users className="w-5 h-5" />,
                  title: "Parent & Student Sign-Up Sheet",
                  desc: "A ready-to-print sign-up table for recruiting your team.",
                },
                {
                  icon: <Mail className="w-5 h-5" />,
                  title: "Volunteer Recruitment Email",
                  desc: "A pre-written email blurb you can copy and send to parents and students.",
                },
                {
                  icon: <Printer className="w-5 h-5" />,
                  title: "Print-Ready Event Plan",
                  desc: "One clean document to hand to your team or keep in your binder.",
                },
                {
                  icon: <Lightbulb className="w-5 h-5" />,
                  title: "Fundraiser Strategy Summary",
                  desc: "Best fit assessment, main profit driver, main execution risk, and recommended focus for your specific event.",
                },
                {
                  icon: <TrendingUp className="w-5 h-5" />,
                  title: "Profit Strategy & Upsell Ideas",
                  desc: "Price check, upsell suggestions, pricing model recommendation, and copy-ready signage language.",
                },
                {
                  icon: <Users className="w-5 h-5" />,
                  title: "Volunteer Briefing Script",
                  desc: "A ready-to-read pre-event briefing for your whole team — food safety, serving flow, and roles.",
                },
                {
                  icon: <MapPin className="w-5 h-5" />,
                  title: "Event Setup Layout",
                  desc: "Step-by-step station layout specific to your meal type so your team knows exactly where everything goes.",
                },
                {
                  icon: <Package className="w-5 h-5" />,
                  title: "Leftover Food Plan",
                  desc: "What to save, what to discard, how to package it, and who makes the call — specific to your meal.",
                },
                {
                  icon: <MessageSquare className="w-5 h-5" />,
                  title: "Parent & Student Communication Pack",
                  desc: "Four ready-to-copy messages: announcement, volunteer request, day-before reminder, and thank-you.",
                },
                {
                  icon: <Shield className="w-5 h-5" />,
                  title: "Risk Plan with Practical Fixes",
                  desc: "Every risk flag paired with a specific, actionable fix so you know exactly how to respond.",
                },
              ].map((f, i) => (
                <div key={i} className="locked-feature">
                  <div className="locked-feature-icon">{f.icon}</div>
                  <div>
                    <div className="locked-feature-title">{f.title}</div>
                    <div className="locked-feature-desc">{f.desc}</div>
                  </div>
                </div>
              ))}
            </div>

            <div className="locked-cta-group">
              <button
                onClick={handlePaymentCTAClick}
                className="btn-locked-cta"
                data-testid="button-unlock-paid"
              >
                Get the Full Event Pack — $19
                <ChevronRight className="w-5 h-5 ml-1" />
              </button>
              <p className="locked-cta-note">
                One-time purchase. Instant access. No account required.
              </p>

              {ENABLE_DEMO_UNLOCK && (
                <button
                  onClick={handleDemoUnlock}
                  className="btn-demo-unlock"
                  data-testid="button-demo-unlock"
                >
                  Demo: Unlock Full Plan
                </button>
              )}
            </div>
          </div>
        </section>
      )}

      {/* ── FULL CONTENT (unlocked only) ────────────────────────── */}
      {unlocked && (
        <>
          {/* Food Quantities */}
          <section className="results-section">
            <h2 className="section-heading">Food Quantity Plan</h2>
            <p className="section-note">
              Quantities include a waste/overage buffer. Adjust based on your knowledge of your crowd.
            </p>
            <div className="table-wrap">
              <table className="data-table" data-testid="table-food-quantities">
                <thead>
                  <tr>
                    <th>Ingredient</th>
                    <th>Quantity to Buy</th>
                    <th>Notes</th>
                  </tr>
                </thead>
                <tbody>
                  {plan.foodQuantities.map((q, i) => (
                    <tr key={i} data-testid={`row-food-${i}`}>
                      <td>{q.ingredient}</td>
                      <td><strong>{q.quantity}</strong></td>
                      <td className="table-note">{q.notes || "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* Tabbed sections */}
          <section className="results-section results-section--tabbed">
            <div className="tab-bar" data-testid="tab-bar">
              {(["shopping", "supplies", "timeline", "volunteers", "email"] as const).map((tab) => (
                <button
                  key={tab}
                  className={`tab-btn ${activeTab === tab ? "tab-btn--active" : ""}`}
                  onClick={() => setActiveTab(tab)}
                  data-testid={`tab-btn-${tab}`}
                >
                  {tab === "shopping" ? "Shopping List" :
                   tab === "supplies" ? "Supplies List" :
                   tab === "timeline" ? "Prep Timeline" :
                   tab === "volunteers" ? "Volunteer Plan" : "Email Blurb"}
                </button>
              ))}
            </div>

            {activeTab === "shopping" && (
              <div className="tab-content" data-testid="tab-content-shopping">
                <p className="tab-intro">
                  Store preference: <strong>{plan.summary.storePreference}</strong>. Prices are estimates and vary by store and region.
                </p>
                {plan.shoppingListGrouped.length > 0 ? (
                  <div className="table-wrap">
                    <table className="data-table" data-testid="table-shopping-list">
                      <thead>
                        <tr>
                          <th>Item</th>
                          <th>Quantity</th>
                          <th>Est. Cost Range</th>
                          <th>Notes</th>
                        </tr>
                      </thead>
                      <tbody>
                        {plan.shoppingListGrouped.map((group) => (
                          <>
                            <tr key={`group-${group.label}`} className="shopping-group-row">
                              <td colSpan={4} className="shopping-group-header-cell">{group.label}</td>
                            </tr>
                            {group.items.map((item, i) => (
                              <tr key={`${group.label}-${i}`} data-testid={`row-shopping-${group.label}-${i}`}>
                                <td>{item.item}</td>
                                <td><strong>{item.quantity}</strong></td>
                                <td>{fmt(item.estimatedCost[0])} – {fmt(item.estimatedCost[1])}</td>
                                <td className="table-note">{item.notes || "—"}</td>
                              </tr>
                            ))}
                          </>
                        ))}
                        <tr className="table-total">
                          <td colSpan={2}><strong>Total Food Cost Estimate</strong></td>
                          <td colSpan={2}><strong>{fmt(plan.costRange[0])} – {fmt(plan.costRange[1])}</strong></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                ) : (
                  <div className="table-wrap">
                    <table className="data-table" data-testid="table-shopping-list">
                      <thead>
                        <tr>
                          <th>Item</th>
                          <th>Quantity</th>
                          <th>Est. Cost Range</th>
                          <th>Notes</th>
                        </tr>
                      </thead>
                      <tbody>
                        {plan.shoppingList.map((item, i) => (
                          <tr key={i} data-testid={`row-shopping-${i}`}>
                            <td>{item.item}</td>
                            <td><strong>{item.quantity}</strong></td>
                            <td>{fmt(item.estimatedCost[0])} – {fmt(item.estimatedCost[1])}</td>
                            <td className="table-note">{item.notes || "—"}</td>
                          </tr>
                        ))}
                        <tr className="table-total">
                          <td colSpan={2}><strong>Total Food Cost Estimate</strong></td>
                          <td colSpan={2}><strong>{fmt(plan.costRange[0])} – {fmt(plan.costRange[1])}</strong></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            )}

            {activeTab === "supplies" && (
              <div className="tab-content" data-testid="tab-content-supplies">
                <div className="table-wrap">
                  <table className="data-table" data-testid="table-supplies-list">
                    <thead>
                      <tr>
                        <th>Supply</th>
                        <th>Quantity</th>
                        <th>Est. Cost Range</th>
                      </tr>
                    </thead>
                    <tbody>
                      {plan.suppliesList.map((item, i) => (
                        <tr key={i} data-testid={`row-supply-${i}`}>
                          <td>{item.item}</td>
                          <td><strong>{item.quantity}</strong></td>
                          <td>
                            {item.estimatedCost[0] === 0
                              ? "Already owned / donated"
                              : `${fmt(item.estimatedCost[0])} – ${fmt(item.estimatedCost[1])}`}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {activeTab === "timeline" && (
              <div className="tab-content" data-testid="tab-content-timeline">
                <div className="timeline-list">
                  {plan.prepTimeline.map((step, i) => (
                    <div key={i} className="timeline-item" data-testid={`timeline-step-${i}`}>
                      <div className="timeline-time">{step.time}</div>
                      <div className="timeline-dot" />
                      <div className="timeline-body">
                        <p className="timeline-task">{step.task}</p>
                        <div className="timeline-meta">
                          <span className={`volunteer-badge volunteer-badge--${step.who.replace(/\s/g, "-").toLowerCase()}`}>
                            {step.who}
                          </span>
                          <span className="timeline-duration">{step.duration}</span>
                        </div>
                        {step.leaderNote && (
                          <p className="timeline-leader-note">
                            <strong>Leader note:</strong> {step.leaderNote}
                          </p>
                        )}
                        {step.watchOut && (
                          <p className="timeline-watch-out">
                            <strong>Watch out:</strong> {step.watchOut}
                          </p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === "volunteers" && (
              <div className="tab-content" data-testid="tab-content-volunteers">
                <div className="volunteer-grid">
                  {plan.volunteerPlan.map((role, i) => (
                    <div key={i} className="volunteer-card" data-testid={`volunteer-role-${i}`}>
                      <div className="volunteer-card-header">
                        <h3 className="volunteer-role">{role.role}</h3>
                        <div className="volunteer-meta">
                          <span className={`volunteer-badge volunteer-badge--${role.type.replace(/\s/g, "-").toLowerCase()}`}>
                            {role.type}
                          </span>
                          <span className="volunteer-count">× {role.count}</span>
                        </div>
                      </div>
                      <ul className="volunteer-duties">
                        {role.duties.map((d, j) => (
                          <li key={j}>{d}</li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
                <div className="signup-section">
                  <h3 className="signup-title">Parent / Student Sign-Up</h3>
                  <p className="signup-desc">
                    Share the email blurb below with your community to recruit volunteers.
                    You can also create a simple sign-up sheet using the printable plan.
                  </p>
                  <div className="signup-table-wrap">
                    <table className="data-table signup-table" data-testid="table-signup">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Role</th>
                          <th>Phone / Email</th>
                          <th>Confirmed</th>
                        </tr>
                      </thead>
                      <tbody>
                        {plan.volunteerPlan.flatMap((role) =>
                          Array.from({ length: role.count }).map((_, j) => (
                            <tr key={`${role.role}-${j}`}>
                              <td className="signup-blank">___________________</td>
                              <td>{role.role}</td>
                              <td className="signup-blank">___________________</td>
                              <td className="signup-blank">___</td>
                            </tr>
                          ))
                        )}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            )}

            {activeTab === "email" && (
              <div className="tab-content" data-testid="tab-content-email">
                <p className="tab-intro">Copy this email to send to your community for volunteer sign-ups.</p>
                <div className="email-blurb-wrap">
                  <pre className="email-blurb" data-testid="text-email-blurb">{plan.emailBlurb}</pre>
                  <button
                    onClick={copyEmailBlurb}
                    className={`copy-btn ${copied ? "copy-btn--copied" : ""}`}
                    data-testid="button-copy-email"
                  >
                    {copied
                      ? <><CheckCircle2 className="w-4 h-4 mr-1" /> Copied!</>
                      : <><Copy className="w-4 h-4 mr-1" /> Copy to Clipboard</>}
                  </button>
                </div>
              </div>
            )}
          </section>

          {/* ── NEW FULL EVENT PACK SECTIONS ───────────────────────── */}

          {/* Strategy Summary */}
          <section className="results-section" data-testid="section-strategy">
            <h2 className="section-heading">Fundraiser Strategy Summary</h2>
            <p className="section-note">
              Tailored to your meal type and event format — what to focus on for a successful event.
            </p>
            <div className="strategy-grid">
              {[
                { label: "Best Fit for This Event", value: plan.strategySummary.bestFit },
                { label: "Main Profit Driver", value: plan.strategySummary.mainProfitDriver },
                { label: "Main Execution Risk", value: plan.strategySummary.mainExecutionRisk },
                { label: "Recommended Focus", value: plan.strategySummary.recommendedFocus },
              ].map((card, i) => (
                <div key={i} className="strategy-card">
                  <div className="strategy-card-label">{card.label}</div>
                  <p className="strategy-card-value">{card.value}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Profit Strategy */}
          <section className="results-section" data-testid="section-profit">
            <h2 className="section-heading">Profit Strategy</h2>
            <p className="section-note">
              Pricing recommendations, upsell ideas, and signage language for your event.
            </p>
            <div className="profit-strategy-block">
              <div className="profit-row">
                <div className="profit-row-label">Price Check</div>
                <p className="profit-row-value">{plan.profitStrategy.priceCheck}</p>
              </div>
              <div className="profit-row">
                <div className="profit-row-label">Recommended Pricing Model</div>
                <p className="profit-row-value">{plan.profitStrategy.pricingModel}</p>
              </div>
              <div className="profit-row">
                <div className="profit-row-label">Upsell Ideas</div>
                <ul className="profit-upsell-list">
                  {plan.profitStrategy.upsellIdeas.map((idea, i) => (
                    <li key={i}>{idea}</li>
                  ))}
                </ul>
              </div>
              <div className="profit-row">
                <div className="profit-row-label">Donation Table Note</div>
                <p className="profit-row-value">{plan.profitStrategy.donationTableNote}</p>
              </div>
              <div className="profit-row">
                <div className="profit-row-label">Suggested Signage</div>
                <div className="profit-signage-list">
                  {plan.profitStrategy.signageLines.map((line, i) => (
                    <div key={i} className="profit-signage-item">{line}</div>
                  ))}
                </div>
              </div>
            </div>
          </section>

          {/* Volunteer Briefing */}
          <section className="results-section" data-testid="section-briefing">
            <h2 className="section-heading">Volunteer Briefing Script</h2>
            <p className="section-note">
              Read this aloud to your whole team before doors open. Copy it to share in advance.
            </p>
            <div className="briefing-wrap">
              <pre className="briefing-pre" data-testid="text-briefing">{plan.volunteerBriefing}</pre>
              <button
                onClick={() => copyText("briefing", plan.volunteerBriefing)}
                className={`copy-btn ${copiedKey === "briefing" ? "copy-btn--copied" : ""}`}
                data-testid="button-copy-briefing"
              >
                {copiedKey === "briefing"
                  ? <><CheckCircle2 className="w-4 h-4 mr-1" /> Copied!</>
                  : <><Copy className="w-4 h-4 mr-1" /> Copy</>}
              </button>
            </div>
          </section>

          {/* Setup Layout */}
          <section className="results-section" data-testid="section-setup">
            <h2 className="section-heading">Event Setup Layout</h2>
            <p className="section-note">
              Station-by-station layout for your meal type. Walk this with your Setup Crew before guests arrive.
            </p>
            <div className="setup-stations">
              {plan.setupLayout.map((station, i) => (
                <div key={i} className="setup-station" data-testid={`setup-station-${i}`}>
                  <div className="setup-station-pos">{station.position}</div>
                  <div>
                    <div className="setup-station-label">{station.label}</div>
                    <div className="setup-station-detail">{station.detail}</div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Communication Pack */}
          <section className="results-section" data-testid="section-comms">
            <h2 className="section-heading">Parent & Student Communication Pack</h2>
            <p className="section-note">
              Four ready-to-copy messages for your event. Click Copy on any message to use it.
            </p>
            <div className="comms-grid">
              {([
                { key: "announcement", label: "Event Announcement", text: plan.commsPack.announcement },
                { key: "volunteerRequest", label: "Volunteer Request", text: plan.commsPack.volunteerRequest },
                { key: "dayBefore", label: "Day-Before Reminder", text: plan.commsPack.dayBeforeReminder },
                { key: "thankYou", label: "Thank-You Message", text: plan.commsPack.thankYou },
              ]).map(({ key, label, text }) => (
                <div key={key} className="comms-block" data-testid={`comms-block-${key}`}>
                  <div className="comms-block-title">{label}</div>
                  <pre className="comms-pre">{text}</pre>
                  <button
                    onClick={() => copyText(key, text)}
                    className={`copy-btn ${copiedKey === key ? "copy-btn--copied" : ""}`}
                    data-testid={`button-copy-${key}`}
                  >
                    {copiedKey === key
                      ? <><CheckCircle2 className="w-4 h-4 mr-1" /> Copied!</>
                      : <><Copy className="w-4 h-4 mr-1" /> Copy</>}
                  </button>
                </div>
              ))}
            </div>
          </section>

          {/* Leftover Plan */}
          <section className="results-section" data-testid="section-leftovers">
            <h2 className="section-heading">Leftover Food Plan</h2>
            <p className="section-note">
              Food safety guidance specific to your meal type. Review this with your Adult Volunteers before the event.
            </p>
            <div className="leftover-grid">
              <div className="leftover-block">
                <div className="leftover-block-title">Can Be Saved</div>
                <ul className="leftover-list leftover-list--save">
                  {plan.leftoverPlan.canSave.map((item, i) => (
                    <li key={i}>{item}</li>
                  ))}
                </ul>
              </div>
              <div className="leftover-block leftover-block--discard">
                <div className="leftover-block-title">Must Be Discarded</div>
                <ul className="leftover-list leftover-list--discard">
                  {plan.leftoverPlan.discard.map((item, i) => (
                    <li key={i}>{item}</li>
                  ))}
                </ul>
              </div>
              <div className="leftover-block">
                <div className="leftover-block-title">How to Package</div>
                <p className="leftover-text">{plan.leftoverPlan.packaging}</p>
              </div>
              <div className="leftover-block">
                <div className="leftover-block-title">Who Makes the Call</div>
                <p className="leftover-text">{plan.leftoverPlan.whoDecides}</p>
              </div>
            </div>
          </section>

          {/* Risk Plan with Fixes */}
          {plan.riskPlan.length > 0 && (
            <section className="results-section" data-testid="section-risk-plan">
              <h2 className="section-heading">Risk Plan</h2>
              <p className="section-note">
                Every risk flag for your event, paired with a specific, actionable fix.
              </p>
              <div className="risk-plan-list">
                {plan.riskPlan.map((item, i) => (
                  <div key={i} className={`risk-plan-item risk-plan-item--${item.level}`} data-testid={`risk-plan-${i}`}>
                    <div className="risk-plan-warning">
                      <span className="warning-icon">
                        {item.level === "error" ? <AlertCircle className="w-5 h-5 text-destructive" /> :
                         item.level === "warning" ? <AlertTriangle className="w-5 h-5 text-amber-500" /> :
                         <Info className="w-5 h-5 text-blue-500" />}
                      </span>
                      <span className="text-sm font-medium">{item.warning}</span>
                    </div>
                    <div className="risk-plan-fix">
                      <span className="risk-fix-label">Fix</span>
                      <p className="risk-fix-text">{item.fix}</p>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Bottom CTA */}
          <div className="results-footer">
            <div className="results-footer-inner">
              <div>
                <h3>Ready to share your plan?</h3>
                <p>Print your plan or save it as a PDF to hand out to your team.</p>
              </div>
              <div className="results-footer-actions">
                <button onClick={onReset} className="btn-secondary" data-testid="button-footer-start-over">Start Over</button>
                <a
                  href="/print"
                  onClick={handlePrintClick}
                  className="btn-primary"
                  target="_blank"
                  data-testid="button-footer-print"
                >
                  <Printer className="w-4 h-4 mr-2" /> Print / Save PDF
                </a>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
