import type { PlannerFormData } from "./types";

export interface SampleTemplate {
  id: string;
  displayName: string;
  mealEmoji: string;
  mealLabel: string;
  formData: PlannerFormData;
}

export const SAMPLE_TEMPLATES: SampleTemplate[] = [
  {
    id: "youth-hotdogs",
    displayName: "Youth Group Hot Dog Fundraiser",
    mealEmoji: "🌭",
    mealLabel: "Hot Dogs",
    formData: {
      eventName: "Youth Group Hot Dog Fundraiser",
      orgType: "Church",
      mealType: "hotdogs",
      attendance: 100,
      mealPrice: 8,
      adultPercent: 60,
      kidPercent: 40,
      storePreference: "Costco",
      prepStartTime: "10:30",
      serveStartTime: "12:00",
      serveEndTime: "14:00",
      adultVolunteers: 5,
      studentVolunteers: 6,
      notes: "Simple outdoor setup using a portable charcoal grill. Hot dogs, chips, and drinks.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "school-burgers",
    displayName: "School Burger Night",
    mealEmoji: "🍔",
    mealLabel: "Burgers",
    formData: {
      eventName: "School Burger Night",
      orgType: "School",
      mealType: "burgers",
      attendance: 200,
      mealPrice: 12,
      adultPercent: 55,
      kidPercent: 45,
      storePreference: "Sam's Club",
      prepStartTime: "16:30",
      serveStartTime: "18:00",
      serveEndTime: "20:00",
      adultVolunteers: 10,
      studentVolunteers: 8,
      notes: "Evening event in the school cafeteria. Pre-sell tickets through teachers.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "mission-potatoes",
    displayName: "Mission Trip Baked Potato Bar",
    mealEmoji: "🥔",
    mealLabel: "Baked Potatoes",
    formData: {
      eventName: "Mission Trip Baked Potato Bar",
      orgType: "Church",
      mealType: "bakedPotatoes",
      attendance: 150,
      mealPrice: 10,
      adultPercent: 70,
      kidPercent: 30,
      storePreference: "Costco",
      prepStartTime: "10:00",
      serveStartTime: "12:00",
      serveEndTime: "14:00",
      adultVolunteers: 8,
      studentVolunteers: 6,
      notes: "Raising funds for summer mission trip. Topping bar includes butter, sour cream, shredded cheese, bacon bits, chives, and broccoli.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "team-tacos",
    displayName: "Team Taco Fundraiser",
    mealEmoji: "🌮",
    mealLabel: "Tacos",
    formData: {
      eventName: "Team Taco Fundraiser",
      orgType: "Sports Team",
      mealType: "tacos",
      attendance: 175,
      mealPrice: 10,
      adultPercent: 50,
      kidPercent: 50,
      storePreference: "Walmart",
      prepStartTime: "16:30",
      serveStartTime: "18:00",
      serveEndTime: "19:30",
      adultVolunteers: 8,
      studentVolunteers: 10,
      notes: "Post-game Friday night fundraiser. Team members serving as student volunteers.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "breakfast-burritos",
    displayName: "Breakfast Burrito Fundraiser",
    mealEmoji: "🌯",
    mealLabel: "Breakfast Burritos",
    formData: {
      eventName: "Breakfast Burrito Fundraiser",
      orgType: "Sports Team",
      mealType: "breakfastBurritos",
      attendance: 120,
      mealPrice: 8,
      adultPercent: 65,
      kidPercent: 35,
      storePreference: "Costco",
      prepStartTime: "07:30",
      serveStartTime: "09:00",
      serveEndTime: "11:00",
      adultVolunteers: 6,
      studentVolunteers: 8,
      notes: "Saturday morning fundraiser. Coffee and orange juice station included.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "spaghetti-dinner",
    displayName: "Spaghetti Dinner",
    mealEmoji: "🍝",
    mealLabel: "Spaghetti",
    formData: {
      eventName: "Annual Spaghetti Dinner",
      orgType: "Church",
      mealType: "spaghetti",
      attendance: 250,
      mealPrice: 13,
      adultPercent: 65,
      kidPercent: 35,
      storePreference: "Sam's Club",
      prepStartTime: "14:00",
      serveStartTime: "17:00",
      serveEndTime: "19:30",
      adultVolunteers: 12,
      studentVolunteers: 10,
      notes: "Sit-down dinner with tables and decorations. Garlic bread and salad included. Silent auction running alongside.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "pancake-breakfast",
    displayName: "Pancake Breakfast",
    mealEmoji: "🥞",
    mealLabel: "Pancakes",
    formData: {
      eventName: "Pancake Breakfast Fundraiser",
      orgType: "Church",
      mealType: "pancakes",
      attendance: 100,
      mealPrice: 8,
      adultPercent: 60,
      kidPercent: 40,
      storePreference: "Local Grocery",
      prepStartTime: "08:00",
      serveStartTime: "09:30",
      serveEndTime: "11:30",
      adultVolunteers: 6,
      studentVolunteers: 5,
      notes: "Sunday morning event after service. Coffee and orange juice included.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "church-lunch",
    displayName: "Church Lunch Fundraiser",
    mealEmoji: "🌭",
    mealLabel: "Hot Dogs",
    formData: {
      eventName: "Church Lunch Fundraiser",
      orgType: "Church",
      mealType: "hotdogs",
      attendance: 125,
      mealPrice: 9,
      adultPercent: 65,
      kidPercent: 35,
      storePreference: "Mixed",
      prepStartTime: "10:30",
      serveStartTime: "12:00",
      serveEndTime: "13:30",
      adultVolunteers: 7,
      studentVolunteers: 5,
      notes: "After-Sunday-service lunch. Quick, simple format with kids' combo option.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "camp-dinner",
    displayName: "Camp Scholarship Dinner",
    mealEmoji: "🍝",
    mealLabel: "Spaghetti",
    formData: {
      eventName: "Camp Scholarship Dinner",
      orgType: "Nonprofit",
      mealType: "spaghetti",
      attendance: 180,
      mealPrice: 14,
      adultPercent: 70,
      kidPercent: 30,
      storePreference: "Costco",
      prepStartTime: "15:00",
      serveStartTime: "18:00",
      serveEndTime: "20:00",
      adultVolunteers: 10,
      studentVolunteers: 8,
      notes: "Raising funds for camp scholarships. Formal-ish sit-down dinner with dessert table.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
  {
    id: "grab-and-go",
    displayName: "After-Service Grab-and-Go",
    mealEmoji: "🌯",
    mealLabel: "Breakfast Burritos",
    formData: {
      eventName: "After-Service Grab-and-Go",
      orgType: "Church",
      mealType: "breakfastBurritos",
      attendance: 90,
      mealPrice: 7,
      adultPercent: 60,
      kidPercent: 40,
      storePreference: "Walmart",
      prepStartTime: "09:00",
      serveStartTime: "10:30",
      serveEndTime: "11:30",
      adultVolunteers: 5,
      studentVolunteers: 4,
      notes: "Quick post-service format — guests grab a foil-wrapped burrito on the way out. Minimal seating needed.",
      customMealName: "",
      customServingSize: "",
      customIngredients: "",
    },
  },
];
